### ISSUE TITLE
无法连接到远程服务器

### ISSUE THREAD

**Issue by Mike-7777777** [xh321/setuDaily#3]
设备已翻墙（不翻一样不行
![微信截图_20210115015110](https://user-images.githubusercontent.com/41225783/104629226-2fcdbd00-56d4-11eb-8d78-5f75da7107db.png)
）。

**Comment by xh321** [comment]
现在最新版支持填代理了
旧版本默认不会走系统代理
请更新最新版（自己下载源码编译一下），我们还支持了多个API
